/* hello.vapi generated by valac 0.56.18, do not modify. */

[CCode (gir_namespace = "hello", gir_version = "1.0")]
namespace Hello {
	[CCode (cheader_filename = "hello.h")]
	public class HelloWorld : GLib.Object {
		public HelloWorld ();
		[Export]
		public void say_hello ();
	}
}
